;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Shinbi.Skill2",DevComment="")
+GameplayTagList=(Tag="Data.CoolDown",DevComment="")
+GameplayTagList=(Tag="Effect.Battle.Damage",DevComment="")
+GameplayTagList=(Tag="Effect.Battle.Gold",DevComment="")
+GameplayTagList=(Tag="Effect.Battle.Mana",DevComment="")
+GameplayTagList=(Tag="Effect.Battle.Shinbi.Skill2",DevComment="")
+GameplayTagList=(Tag="Effect.Battle.Shinbi.Skill2Time",DevComment="")
+GameplayTagList=(Tag="Effect.Item.HPPotion",DevComment="")
+GameplayTagList=(Tag="Effect.Item.Weapon",DevComment="")
+GameplayTagList=(Tag="Effect.Skill.CoolDown1",DevComment="")
+GameplayTagList=(Tag="Effect.Skill.CoolDown2",DevComment="")
+GameplayTagList=(Tag="Event.Shinbi.Skill2",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Battle.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Battle.Shinbi.Skill2",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Item.HPPotion",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Item.Weapon",DevComment="")

